name: Api Deploy

on:
  push:
    branches:
    - main
    - feature/**
   workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: func-amw-dev-aue-001  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './output' 
  DOTNET_VERSION: '3.1.x'          

jobs:

  build:

    environment: DEV
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore api/AzureModernWeb.sln

    - name: Build
      run: dotnet build --no-restore ./api/AzureModernWeb.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal ./api/AzureModernWeb.sln

    - name: Publish
      run: dotnet publish --no-build  --output ./output ./api/BankingApi/BankingApi.csproj

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: BankingAPI
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:

    runs-on: ubuntu-latest
    needs: [build]
    environment: DEV

    steps:

    - name: Download website
      uses: actions/download-artifact@v1
      with:
        name: BankingAPI
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Functions Action
      uses: Azure/functions-action@v1.3.1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
