on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - "infra/**"

name: Azure Deploy

jobs:
  deploy:
    environment: DEV
    runs-on: ubuntu-latest

    env:
      LOCATION: "Australia East"
      APPLICATION_NAME: "amw-dev-aue-001"

    steps:
      - uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Infrastructure ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infra/main.json
          parameters:
            applicationName="${{ env.APPLICATION_NAME }}"
            location="${{ env.LOCATION }}"
            objectId="${{ secrets.AZURE_SP_OBJECT_ID }}"

      # - name: Deploy Infrastructure
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az deployment sub create -f ./infra/main.bicep --name "rg-${{ env.APPLICATION_NAME }}" --location="${{ env.LOCATION }}" --parameters applicationName="${{ env.APPLICATION_NAME }}" objectId="${{ secrets.AZURE_SP_OBJECT_ID }}"
