on:
  push:
    branches:
      - main
      - feature/**
    # paths:
    #   - "infra/**"

name: Azure Deploy

jobs:
  deploy:
    environment: DEV
    runs-on: ubuntu-latest

    env:
      LOCATION: "Australia East"
      APP_NAME: "amw-dev-aue-001"

    steps:
      - uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install bicep for az cli
        run: |
          apk update
          apk install libc6-compat
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep

      - name: Deploy Infrastructure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create -f ./infra/main.bicep --name "rg-${{ env.APP_NAME }}" --location="${{ env.LOCATION }}" --parameters applicationName="${{ env.APP_NAME }}" objectId="${{ secrets.AZURE_SP_OBJECT_ID }}"
