on:
  push:
    branches:
      - main
      - feature/**
    # paths:
    #   - "infra/**"

name: Azure Deploy

jobs:
  deploy:
    environment: DEV
    runs-on: windows-latest

    env:
      LOCATION: "Australia East"
      APP_NAME: "amw-dev-aue-001"

    steps:
      - uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create -f ./infra/main.bicep --name "rg-${{ env.APP_NAME }}" --location="${{ env.LOCATION }}" --parameters applicationName="${{ env.APP_NAME }}" objectId="${{ secrets.AZURE_SP_OBJECT_ID }}"
