on: [push]

name: Azure Deploy

jobs:

  deploy:
    environment: DEV
    runs-on: ubuntu-latest
    steps:

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Run Az CLI script
      run: |
        az group show --name "rg-amw-dev-aue-001"