name: Azure Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy-dev:
    environment: DEV
    runs-on: ubuntu-latest    

    env:
      AZURE_LOCATION: 'Australia East'
      STAGE: 'dev'
      LOCATION_SHORT: 'aue'
      PREFIX: 'amw'
      POSTFIX: '001'

    steps:
    - uses: actions/checkout@v2
    - name: 'Deploy Stage: ${{ env.STAGE }}'
      id: deploy-stage
      uses: ./.github/actions/deploy-stage
      with:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        azure-resource-group: ${{ secrets.AZURE_RG }}
        azure-sp-object-id: ${{ secrets.AZURE_SP_OBJECT_ID }}
        azure-primary-location: ${{ env.AZURE_LOCATION }}
        environment: ${{ env.STAGE }}
        location-short: ${{ env.LOCATION_SHORT }}
        prefix: ${{ env.PREFIX }}
        postfix: ${{ env.POSTFIX }}
